version: '3'
services:
  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./app/mqtt_service/mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "healthcheck"]
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 3
  
  data_persistence_service:
    build: ./app/data_persistence_service
    ports:
      - 5000:5000
    volumes:
      - ./app/data_persistence_service:/app
    depends_on:
      - mqtt_broker
    links:
      - mqtt_broker

  soil_sensing_service:
    build: ./app/soil_sensing_service
    volumes:
      - ./app/soil_sensing_service:/app
    depends_on:
      - mqtt_broker
    links:
      - mqtt_broker
    privileged: true

  day_night_led_service:
    build: ./app/day_night_led_service
    volumes:
      - ./app/day_night_led_service:/app
    depends_on:
      - mqtt_broker
    links:
      - mqtt_broker
    privileged: true

  led_alert_service:
    build: ./app/led_alert_service
    volumes:
      - ./app/led_alert_service:/app
    depends_on:
      - mqtt_broker
    links:
      - mqtt_broker
    privileged: true

  web_gui_service:
    build: ./app/web_gui_service
    ports:
      - 8080:8080
    volumes:
      - ./app/web_gui_service:/app
    depends_on:
      - mqtt_broker
    links:
      - mqtt_broker
